# general settings
name: train_flow_v9
model_type: SRFLOW
num_gpu: auto
scale: 4 # used in validation ( i guess )
manual_seed:

# ----------------- options for synthesizing training data in RealESRGANModel ----------------- #

# the first degradation process
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# the second degradation process
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

gt_size: 512
queue_size: 8

# dataset and data loader settings
datasets:
  train:
    name: dataset
    type: RealESRGANDataset
    dataroot_gt: /
    meta_info: meta_info.txt
    io_backend:
      type: disk

    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    gt_size: 512
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
     name: validation
     type: PairedImageDataset
     dataroot_gt: tests/data/gt
     dataroot_lq: tests/data/lq_4
     io_backend:
       type: disk

# network structures
network_g:
  type: RRDB_UNet_v9_t
  num_in_ch: 6
  num_out_ch: 3
  highway_channels_base: 64
  processing_channels_base: 32
  num_grow_ch_base: 16
  encoder_blocks: 2
  decoder_blocks: 2
  ae_channel_multipliers: [1,2,4,12]
  body_rrdb_blocks: 2
  body_dit_blocks: 24
  dit_heads: 12
  dit_head_dim: 64
  t_hidden_dim: 1024
  checkpoint: False

# path
path:
  pretrain_network_g:
  param_key_g: params_ema
  strict_load_g: true
  resume_state:

# training settings
train:
  #ema_decay: 0.9999
  ema_decay: 0.0
  optim_g:
    type: AdamW8bit
    lr: 0.0001
    weight_decay: 0.00001
    betas: [0.9, 0.99]

  scheduler:
      type: MultiStepLR
      milestones: [2000000, 4000000, 6000000, 8000000, 10000000, 12000000, 14000000]
      gamma: 0.7

  total_iter: 16000000
  warmup_iter: 1000
  gradient_accumulation_steps: 16
  min_scale: 1
  max_scale: 6
  use_compile: True


  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
   val_freq: 10000
   save_img: True
   inference_steps: 16

   metrics:
     psnr: # metric name
       type: calculate_psnr
       crop_border: 4
       test_y_channel: false
     ssim:
       type: calculate_ssim
       crop_border: 4
       test_y_channel: false
     niqe:
         type: calculate_niqe
         crop_border: 4
         better: lower


# logging settings
logger:
  print_freq: 64
  save_checkpoint_freq: 50000
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500
